### Log ind med en bruger
POST http://localhost:7007/api/auth/login
Content-Type: application/json

{
  "email": "hanni@email.dk",
  "password": "1234"
}

### Registrering af en bruger
POST http://localhost:7007/api/auth/register
Content-Type: application/json

{
  "email": "hanni@email.dk",
  "password": "1234"
}

### Get all items
GET http://localhost:7007/api/items

### Get item by id
GET http://localhost:7007/api/items/1

### Upload item
POST http://localhost:7007/api/items/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJMQUhZIiwic3ViIjoiaGFubmlAZW1haWwuZGsiLCJleHAiOjE3MTU5NDAwMTAsImVtYWlsIjoiaGFubmlAZW1haWwuZGsiLCJyb2xlcyI6InVzZXIifQ.DyGSWbUKhDqRka6q8b965MCQX1eqzu49tzxxGc9z6xw

{
  "title": "Vintage Chair",
  "description": "A great vintage chair",
  "price": 150.0,
  "fullName": "John Doe",
  "address": "123 Elm St",
  "postalCode": 2800,
  "phoneNumber": 12345678,
  "user": {
     "email": "ahmad@email.dk"
  }
}

### Update item
PUT http://localhost:7007/api/items/ahmad@email.dk
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJMQUhZIiwic3ViIjoiaGFubmlAZW1haWwuZGsiLCJleHAiOjE3MTU5NDAwMTAsImVtYWlsIjoiaGFubmlAZW1haWwuZGsiLCJyb2xlcyI6InVzZXIifQ.DyGSWbUKhDqRka6q8b965MCQX1eqzu49tzxxGc9z6xw

{
  "id": 2,
  "title": "Vintage Chairr",
  "description": "A great vintage chair",
  "price": 150.0,
  "fullName": "John Doe",
  "address": "123 Elm St",
  "postalCode": 2800,
  "status": true,
  "phoneNumber": 12345678
}

### Delete item
DELETE http://localhost:7007/api/items/ahmad@email.dk
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJMQUhZIiwic3ViIjoiaGFubmlAZW1haWwuZGsiLCJleHAiOjE3MTU5NDAwMTAsImVtYWlsIjoiaGFubmlAZW1haWwuZGsiLCJyb2xlcyI6InVzZXIifQ.DyGSWbUKhDqRka6q8b965MCQX1eqzu49tzxxGc9z6xw

4