### Log ind med en bruger
POST http://localhost:7007/api/auth/login
Content-Type: application/json

{
  "email": "test",
  "password": "1234"
}

### Registrering af en bruger
POST http://localhost:7007/api/auth/register
Content-Type: application/json

{
  "email": "test",
  "password": "1234"
}

### Get all items
GET http://localhost:7007/api/items

### Get all items
GET http://localhost:7007/api/items/test
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJMQUhZIiwic3ViIjoidGVzdCIsImV4cCI6MTcxNjI3OTIwOSwiZW1haWwiOiJ0ZXN0Iiwicm9sZXMiOiJ1c2VyIn0.mGLXTq3737N36WEzFIG8majVz6qV5VBT1lbNGNiHxEw

### Get item by id
GET http://localhost:7007/api/items/2

### Upload item
POST http://localhost:7007/api/items/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJMQUhZIiwic3ViIjoidGVzdCIsImV4cCI6MTcxNTk0NTA2MSwiZW1haWwiOiJ0ZXN0Iiwicm9sZXMiOiJ1c2VyIn0.3XUti-oi37rapnyRjpzKtUgPIYAZRchiBwT4wLI7_gY

{
  "title": "Vintage Chair",
  "description": "A great vintage chair",
  "price": 150.0,
  "fullName": "John Doe",
  "address": "123 Elm St",
  "zipCode": 2800,
  "phoneNumber": 12345678,
  "user": {
     "email": "test"
  }
}

### Update item
PUT http://localhost:7007/api/items/test
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJMQUhZIiwic3ViIjoidGVzdCIsImV4cCI6MTcxNTk0NTA2MSwiZW1haWwiOiJ0ZXN0Iiwicm9sZXMiOiJ1c2VyIn0.3XUti-oi37rapnyRjpzKtUgPIYAZRchiBwT4wLI7_gY

{
  "id": 2,
  "title": "Vintage Chairr",
  "description": "A great vintage chair",
  "price": 150.0,
  "fullName": "John Doe",
  "address": "123 Elm St",
  "zipCode": 2800,
  "status": true,
  "phoneNumber": 12345678
}

### Delete item
DELETE http://localhost:7007/api/items/ahmad@email.dk
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJMQUhZIiwic3ViIjoidGVzdCIsImV4cCI6MTcxNTk0NTA2MSwiZW1haWwiOiJ0ZXN0Iiwicm9sZXMiOiJ1c2VyIn0.3XUti-oi37rapnyRjpzKtUgPIYAZRchiBwT4wLI7_gY

3